/** Declaration file generated by dts-gen */

export = editor;

declare function editor(file: any, opts: any, cb: any): void;

declare namespace editor {
    const prototype: {
    };

}

