/** Declaration file generated by dts-gen */

export const spaces: any;

export function readFile(file: any, options: any, callback: any): any;

export function readFileSync(file: any, options: any): any;

export function writeFile(file: any, obj: any, options: any, callback: any): void;

export function writeFileSync(file: any, obj: any, options: any): any;

export namespace readFile {
    const prototype: {
    };

}

export namespace readFileSync {
    const prototype: {
    };

}

export namespace writeFile {
    const prototype: {
    };

}

export namespace writeFileSync {
    const prototype: {
    };

}

